version: 2
jobs:
  build:
    branches:
      only:
        - master
        - dev

    docker:
      - image: circleci/node:10.9.0-browsers
      - image: circleci/mysql:5.7.23-ram

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Adjust known_hosts
          command: ssh-keyscan 185.72.246.73 >> ~/.ssh/known_hosts

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # install deps
      - run: sudo apt-get update
      - run: sudo apt-get install mysql-client lame mediainfo

      # create DB
      - run: mysql -h $IE_DB_HOSTNAME -u $IE_DB_USERNAME -e "CREATE DATABASE $IE_DB_NAME"

      # Run tests
      - run: npm run check

      # Run server
      - run: npm run build
      - run:
          name: Run server
          command: npm run start:prod
          background: true
      - run: sleep 5

      # Run browser tests
      - run: npm run testcafe
  deploy:
    steps:
      - run: npm run deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
